name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check for new version
        id: check_version
        run: |
          CURRENT_VERSION=$(npm show . version)
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$PACKAGE_VERSION" != "$CURRENT_VERSION" ]; then
            echo "::set-output name=new_version::true"
          else
            echo "::set-output name=new_version::false"
          fi

      - name: Publish to npm
        if: steps.check_version.outputs.new_version == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        if: steps.check_version.outputs.new_version == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.sha }}
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}